@startuml simple-ingress

footer Kubernetes Plant-UML
' scale max 1024 width

skinparam nodesep 30
skinparam ranksep 30

' Azure
!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/release/2-1/dist

!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureSimplified.puml

' Kubernetes
!define KubernetesPuml https://raw.githubusercontent.com/dcasati/kubernetes-PlantUML/master/dist

!includeurl KubernetesPuml/kubernetes_Common.puml
!includeurl KubernetesPuml/kubernetes_Context.puml
!includeurl KubernetesPuml/kubernetes_Simplified.puml
!includeurl KubernetesPuml/OSS/KubernetesSvc.puml
'!includeurl KubernetesPuml/OSS/KubernetesPod.puml
!includeurl KubernetesPuml/OSS/KubernetesIng.puml
!includeurl KubernetesPuml/OSS/KubernetesDeploy.puml


actor "User" as userAlias
left to right direction

' Kubernetes Components
Cluster_Boundary(cluster, "Kubernetes Cluster") {
    Namespace_Boundary(default, "default") {
        KubernetesIng(ingress, "API Gateway", "")
        KubernetesSvc(minio, "Minio", "")
        KubernetesSvc(key,"Keycloak", "")
        KubernetesSvc(o2p, "oauth2-proxy", "")
    }
}

'Static Web
Rel(userAlias, ingress, "Get index.html", "0")
Rel(ingress, o2p,"valid credential", "1")
Rel(o2p, key,"Login", "2")
Rel(ingress, minio, "get index.html", "3")

@enduml