@startuml parse-forecast

footer Kubernetes Plant-UML
' scale max 1024 width

skinparam nodesep 30
skinparam ranksep 30

' Azure
!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/release/2-1/dist

!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureSimplified.puml

' Kubernetes
!define KubernetesPuml https://raw.githubusercontent.com/dcasati/kubernetes-PlantUML/master/dist

!includeurl KubernetesPuml/kubernetes_Common.puml
!includeurl KubernetesPuml/kubernetes_Context.puml
!includeurl KubernetesPuml/kubernetes_Simplified.puml
!includeurl KubernetesPuml/OSS/KubernetesSvc.puml
!includeurl KubernetesPuml/OSS/KubernetesDeploy.puml

left to right direction

' Kubernetes Components
Cluster_Boundary(cluster, "Kubernetes Cluster") {
    Namespace_Boundary(default, "default") {
        KubernetesSvc(mongo, "Mongo", "")
        KubernetesSvc(minio, "Minio", "")
    }

    Namespace_Boundary(nsfn, "openfaas-fn") {
        KubernetesSvc(fnpf, "[function]\nparse-forecast", "")
    }

    Namespace_Boundary(ns, "openfaas") {
        KubernetesSvc(ofg, "openfaas Gateway", "")
        KubernetesSvc(nats, "nats", "")
        KubernetesDeploy(natsconector, "nats-connector","")
    }

}

Rel_L(minio, nats, "Event new file", "1")
Rel_U(nats, natsconector, "Queme message\nNew file", "2")
Rel(natsconector, ofg,  "Message\nNew file", "3")
Rel(ofg, fnpf, "Message\nNew file", "4")
Rel(fnpf, mongo, "Parse forecast file", "5")

@enduml