apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: grafana.192.168.0.100.nip.io
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 3000

